baseURL = "https://blago-nko.github.io/web-moisites/"
languageCode = "ru-ru"
title = "web-moisites"

[params]
  description = "Миграция с Blogger на Hugo"
  noindex = true

[markup.goldmark.renderer]
  unsafe = true
uglyURLs = true
